name: py3
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - cudatoolkit=10.2.89
  - freetype=2.10.2
  - intel-openmp=2020.1
  - jpeg=9b
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.5
  - numpy-base=1.18.5
  - olefile=0.46
  - openssl=1.1.1g
  - pillow=7.1.2
  - pip=20.1.1
  - python=3.7.7
  - pytorch=1.5.1
  - readline=8.0
  - setuptools=47.3.1
  - six=1.15.0
  - sqlite=3.32.3
  - tk=8.6.10
  - torchvision=0.6.1
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - absl-py==0.9.0
    - appdirs==1.4.4
    - attrs==19.3.0
    - black==19.10b0
    - cachetools==4.1.1
    - chardet==3.0.4
    - click==7.1.2
    - cloudpickle==1.3.0
    - cycler==0.10.0
    - flake8==3.8.3
    - flake8-black==0.2.0
    - future==0.18.2
    - google-auth==1.18.0
    - google-auth-oauthlib==0.4.1
    - greenlet==0.4.16
    - grpcio==1.30.0
    - gym==0.17.2
    - idna==2.10
    - importlib-metadata==1.7.0
    - isort==5.1.4
    - kiwisolver==1.2.0
    - markdown==3.2.2
    - matplotlib==3.3.0
    - mccabe==0.6.1
    - msgpack==1.0.0
    - oauthlib==3.1.0
    - pathspec==0.8.0
    - protobuf==3.12.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.6.0
    - pyflakes==2.2.0
    - pyglet==1.5.0
    - pynvim==0.4.1
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytorch-lightning==0.8.4
    - pyyaml==5.3.1
    - regex==2020.6.8
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scipy==1.5.2
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.7.0
    - toml==0.10.1
    - tqdm==4.47.0
    - typed-ast==1.4.1
    - urllib3==1.25.9
    - werkzeug==1.0.1
    - zipp==3.1.0

